# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb7ce8a08ffafa9a0e94008a66aa9ae87012a5af2838ac3f2a2e14f60bdb5e54be18c4ff3bc242313a3dae3ff3251d2a7d6c4a1d779944aa22485724b682c02e

test:
  secret_key_base: 434264c22163c3ea8bc40c7fa1c6d22b7b8a87b5d132e469e1a9cbad12bd1865c4ba91322d8d48e79554ba41082b45662b26f0ab4423acd88bf6e31f95139221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
